#postgre Sql
spring.datasource.url=jdbc:postgresql://dpg-d83ka40js32c73chkj30-a.frankfurt-postgres.render.com/cashpilot_0v68
spring.datasource.username=cashpilot_0v68_user
spring.datasource.password=veWodXuH9TeyZq0ypnVujgC5uUE9s7ed
