#postgre Sql
spring.datasource.url=jdbc:postgresql://localhost:5432/cashpilot
spring.datasource.username=postgres
spring.datasource.password=123456

server.servlet.context-path=/api/v1.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Email configuration
spring.mail.host = smtp-relay.brevo.com
spring.mail.port = 587
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.smtp.from=${BREVO_FROM_EMAIL}

jwt.secret=B2mIF3Cv4oPzj2N5aJLyhR7N6mH0F+fdzK2E2a4q8zL6A1ks9Qd0wGqzTt1bG3tW6pYzQFf9kV3bP2H7mC4xSg==

money.manger.frontend.url =${CASH_PILOT_FRONTEND_URL}
money.manger.backend.url =${CASH_PILOT_BACKEND_URL}
app.activation.url=http://localhost:8080

spring.profiles.active=prod